# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/scDenorm',
                'doc_host': 'https://changebio.github.io',
                'git_url': 'https://github.com/changebio/scDenorm',
                'lib_path': 'scDenorm'},
  'syms': {'scDenorm.core': {'scDenorm.core.foo': ('core.html#foo', 'scDenorm/core.py')}}}