# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/scDenorm',
                'doc_host': 'https://changebio.github.io',
                'git_url': 'https://github.com/changebio/scDenorm',
                'lib_path': 'scDenorm'},
  'syms': { 'scDenorm.core': {'scDenorm.core.foo': ('examples.html#foo', 'scDenorm/core.py')},
            'scDenorm.denorm': { 'scDenorm.denorm.check_plot': ('scdenorm.html#check_plot', 'scDenorm/denorm.py'),
                                 'scDenorm.denorm.check_unscale': ('scdenorm.html#check_unscale', 'scDenorm/denorm.py'),
                                 'scDenorm.denorm.get_scaling_factor': ('scdenorm.html#get_scaling_factor', 'scDenorm/denorm.py'),
                                 'scDenorm.denorm.get_scaling_factor_1': ('scdenorm.html#get_scaling_factor_1', 'scDenorm/denorm.py'),
                                 'scDenorm.denorm.scdenorm': ('scdenorm.html#scdenorm', 'scDenorm/denorm.py'),
                                 'scDenorm.denorm.select_base': ('scdenorm.html#select_base', 'scDenorm/denorm.py'),
                                 'scDenorm.denorm.unscale_mat': ('scdenorm.html#unscale_mat', 'scDenorm/denorm.py')}}}